### ISSUE TITLE
How can I evaluate the dataset that I have trained on：

### ISSUE THREAD

**Issue by TanXi789** [j-morano/rrwnet#3]
How can I evaluate the dataset that I have trained on? Is it done using the compare_results.py file? How should I organize my dataset?

**Comment by j-morano** [comment]
Hello. Thank you very much for your feedback. Since you are the second person to ask about how to run the evaluation code, I have made some changes to the documentation to make it clearer, and to the code to make it easier to use. You can check out the new instructions and code in the [eval/](https://github.com/j-morano/rrwnet/tree/main/eval) directory. If you have any questions, do not hesitate to contact me again through this issue or open another one.
